### PR TITLE
Split out from init

### PR DESCRIPTION
**Pull request by blag**
This PR builds on PR #19 (convert exceptions to errors).

This moves the code that was in `__init__.py` into the new `keys.py`, and includes `import` statements to maintain reverse compatibility.

I broke this PR out into 2 commits (ignoring the commit from #19) to make each one easy to review. Commit 4c7a9f1 may not pass the tests, so if/when you merge this, you'll want to use the "Squash and Merge" option. I'll try to keep this PR rebased off of your `master` branch to make it easy to do.

### CODE REVIEW

**Comment by ojarva** [comment]
Thank you! I'm traveling until Thursday. I'll take a closer look as soon as possible after returning home.

**Comment by blag** [comment]
Totally offtopic: How do you get this badge on the list of checks?

screen shot 2016-10-31 at 1 18 40 pm

Is it a GitHub setting or a Travis setting?

**Comment by ojarva** [comment]
It's in github project settings - you can designate any check as required, and prevent merging if it does not either run or pass.

**Comment by blag** [comment]
Oh cool, I didn't know you could do that. I'm only the maintainer of a few projects, not the owner, so I can't see the settings available for integrating with CI tools. Thanks and safe travels!

**Pull request merged**
