### PR TITLE
Improve packaging

### PR DESCRIPTION
**Pull request by koobs**

### CODE REVIEW

**Comment by ojarva** [comment]
Tests are failing as packages is already specified in setup.py

**Comment by koobs** [comment]
Apologies, I missed that in my haste to submit. Tested sdist generation and sdist contents (see below). 

Please check/confirm your end before merging.

```
running sdist
running egg_info
writing requirements to sshpubkeys.egg-info/requires.txt
writing sshpubkeys.egg-info/PKG-INFO
writing top-level names to sshpubkeys.egg-info/top_level.txt
writing dependency_links to sshpubkeys.egg-info/dependency_links.txt
reading manifest file 'sshpubkeys.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sshpubkeys.egg-info/SOURCES.txt'
running check
creating sshpubkeys-3.1.0
creating sshpubkeys-3.1.0/sshpubkeys
creating sshpubkeys-3.1.0/sshpubkeys.egg-info
creating sshpubkeys-3.1.0/tests
copying files to sshpubkeys-3.1.0...
copying .travis.yml -> sshpubkeys-3.1.0
copying LICENSE.txt -> sshpubkeys-3.1.0
copying MANIFEST.in -> sshpubkeys-3.1.0
copying README.rst -> sshpubkeys-3.1.0
copying requirements.txt -> sshpubkeys-3.1.0
copying setup.cfg -> sshpubkeys-3.1.0
copying setup.py -> sshpubkeys-3.1.0
copying sshpubkeys/__init__.py -> sshpubkeys-3.1.0/sshpubkeys
copying sshpubkeys/exceptions.py -> sshpubkeys-3.1.0/sshpubkeys
copying sshpubkeys/keys.py -> sshpubkeys-3.1.0/sshpubkeys
copying sshpubkeys.egg-info/PKG-INFO -> sshpubkeys-3.1.0/sshpubkeys.egg-info
copying sshpubkeys.egg-info/SOURCES.txt -> sshpubkeys-3.1.0/sshpubkeys.egg-info
copying sshpubkeys.egg-info/dependency_links.txt -> sshpubkeys-3.1.0/sshpubkeys.egg-info
copying sshpubkeys.egg-info/requires.txt -> sshpubkeys-3.1.0/sshpubkeys.egg-info
copying sshpubkeys.egg-info/top_level.txt -> sshpubkeys-3.1.0/sshpubkeys.egg-info
copying tests/__init__.py -> sshpubkeys-3.1.0/tests
copying tests/authorized_keys.py -> sshpubkeys-3.1.0/tests
copying tests/invalid_authorized_keys.py -> sshpubkeys-3.1.0/tests
copying tests/invalid_keys.py -> sshpubkeys-3.1.0/tests
copying tests/invalid_options.py -> sshpubkeys-3.1.0/tests
copying tests/test_dsa_keys_failing.py -> sshpubkeys-3.1.0/tests
copying tests/valid_keys.py -> sshpubkeys-3.1.0/tests
copying tests/valid_keys_rfc4716.py -> sshpubkeys-3.1.0/tests
copying tests/valid_options.py -> sshpubkeys-3.1.0/tests
Writing sshpubkeys-3.1.0/setup.cfg
creating dist
Creating tar archive
removing 'sshpubkeys-3.1.0' (and everything under it)
```
tar -tvzf dist/sshpubkeys-3.1.0.tar.gz
```
x sshpubkeys-3.1.0/
x sshpubkeys-3.1.0/tests/
x sshpubkeys-3.1.0/tests/authorized_keys.py
x sshpubkeys-3.1.0/tests/invalid_options.py
x sshpubkeys-3.1.0/tests/valid_keys.py
x sshpubkeys-3.1.0/tests/invalid_keys.py
x sshpubkeys-3.1.0/tests/test_dsa_keys_failing.py
x sshpubkeys-3.1.0/tests/__init__.py
x sshpubkeys-3.1.0/tests/invalid_authorized_keys.py
x sshpubkeys-3.1.0/tests/valid_keys_rfc4716.py
x sshpubkeys-3.1.0/tests/valid_options.py
x sshpubkeys-3.1.0/setup.cfg
x sshpubkeys-3.1.0/.travis.yml
x sshpubkeys-3.1.0/LICENSE.txt
x sshpubkeys-3.1.0/sshpubkeys/
x sshpubkeys-3.1.0/sshpubkeys/keys.py
x sshpubkeys-3.1.0/sshpubkeys/__init__.py
x sshpubkeys-3.1.0/sshpubkeys/exceptions.py
x sshpubkeys-3.1.0/sshpubkeys.egg-info/
x sshpubkeys-3.1.0/sshpubkeys.egg-info/dependency_links.txt
x sshpubkeys-3.1.0/sshpubkeys.egg-info/requires.txt
x sshpubkeys-3.1.0/sshpubkeys.egg-info/top_level.txt
x sshpubkeys-3.1.0/sshpubkeys.egg-info/PKG-INFO
x sshpubkeys-3.1.0/sshpubkeys.egg-info/SOURCES.txt
x sshpubkeys-3.1.0/PKG-INFO
x sshpubkeys-3.1.0/requirements.txt
x sshpubkeys-3.1.0/setup.py
x sshpubkeys-3.1.0/README.rst
x sshpubkeys-3.1.0/MANIFEST.in
```

**Review by ojarva — CHANGES_REQUESTED** [review]
Hi @koobs !

I'm sorry I have kept you waiting for so long. Could you please rebase this to master (to get new tests & there's a very simple conflict; your version is better what is in master)? If you could do that, I'll merge this right away (well, after the tests pass, but that shouldn't take long with new github actions).

**Comment by ojarva** [comment]
If you are planning on fixing this, please reopen this PR after rebasing to master - I think it would be useful change.

**Pull request closed without merging**
